import { extraRaw } from './ideas-extra.js';
// Sources are primary pages from overseas operators, checked 18 September 2026.
// Each local fit, competition estimate, and editorial rating is a hypothesis.
const raw = [
  // title | category | summary | customer | model | complexity | overseas example | url | observable evidence | local hypothesis | first experiment | main risk | ratings
  ["Pasar gawai rekondisi terstandar","Produk","Marketplace perangkat bekas dengan grading kondisi, garansi, dan inspeksi mitra.","Pembeli gawai hemat & toko servis","Marketplace","Tinggi","Back Market","https://www.backmarket.com/en-us","Back Market menampilkan perangkat rekondisi dengan standar kondisi dan proteksi pembelian.","Kepercayaan terhadap kualitas bisa menjadi pembeda dibanding listing barang bekas biasa.","Kurasi 20 unit dari 3 teknisi; ukur retur dan konversi garansi.","Kontrol mutu dan biaya klaim.",[4,3,4,5]],
  ["Langganan perangkat untuk tim kecil","Produk","Sewa laptop dan perangkat kerja bulanan dengan opsi ganti dan perawatan.","UMKM & tim proyek","Langganan","Tinggi","Grover","https://www.grover.com/","Grover menawarkan penyewaan teknologi dengan periode fleksibel.","Tim yang enggan belanja modal mungkin bersedia membayar biaya perangkat bulanan.","Tawarkan 10 laptop pada 3 usaha; hitung utilisasi dan gagal bayar.","Modal inventaris dan kerusakan.",[4,3,4,5]],
  ["Titip jual barang anak berkualitas","Produk","Layanan sortir, foto, dan jual ulang pakaian serta perlengkapan anak.","Orang tua urban","Managed service","Sedang","ThredUp","https://www.thredup.com/","ThredUp mengoperasikan penjualan kembali dan konsinyasi pakaian secara daring.","Siklus ukuran anak yang cepat dapat menciptakan pasokan berulang.","Ambil 100 barang dari 20 keluarga; ukur waktu terjual dan ongkos sortir.","Margin per item kecil.",[4,3,3,3]],
  ["Sewa perlengkapan bayi saat bepergian","Produk","Antar stroller, car seat, dan ranjang bayi ke penginapan sesuai tanggal perjalanan.","Keluarga wisatawan","Marketplace","Sedang","BabyQuip","https://www.babyquip.com/","BabyQuip mempertemukan keluarga dengan penyedia perlengkapan bayi untuk perjalanan.","Kota wisata mungkin memiliki kebutuhan musiman yang cukup untuk penyewa lokal.","Rekrut 5 penyedia di satu kota wisata dan uji 30 pemesanan.","Kebersihan, keamanan, dan logistik.",[4,2,4,3]],
  ["Sewa alat hobi antar tetangga","Produk","Penyewaan kamera, alat kerja, dan alat acara dengan deposit serta verifikasi.","Kreator & penghobi","Marketplace","Tinggi","Hygglo","https://hygglo.com/uk","Hygglo menampilkan peminjaman barang milik orang lain secara lokal.","Barang yang jarang dipakai dapat menghasilkan pendapatan bila risiko kerusakan terkelola.","Uji 50 listing di satu komunitas; catat transaksi dan insiden.","Penipuan, kerusakan, dan asuransi.",[3,3,3,4]],
  ["Lemari bersama untuk acara","Produk","Sewa pakaian pesta dan aksesori dari pemilik lokal dengan layanan cuci.","Pengunjung acara & pemilik busana","Marketplace","Sedang","By Rotation","https://byrotation.com/","By Rotation memfasilitasi penyewaan dan penjualan busana dari komunitas.","Busana yang dipakai sesekali bisa berputar dalam komunitas perkotaan.","Uji 30 busana dan 2 mitra laundry selama satu musim acara.","Ukuran, kondisi barang, dan logistik.",[3,3,3,3]],
  ["Grosir kurasi untuk toko independen","Produk","Katalog merek kecil, pembelian ulang, dan termin pembayaran untuk retailer.","Toko lokal & merek baru","Marketplace","Tinggi","Faire","https://www.faire.com/","Faire mempertemukan retailer independen dengan merek grosir.","Kurasi niche dapat membantu toko menemukan pemasok di luar jaringan distributor besar.","Uji 15 merek dan 20 toko pada satu kategori.","Kredit dagang dan akuisisi dua sisi.",[4,4,4,5]],
  ["Bagi pakai armada kendaraan menganggur","Produk","Pemilik armada kecil menyewakan mobil pada jam kosong dengan serah terima terkelola.","Pemilik armada & penyewa","Marketplace","Tinggi","Turo","https://turo.com/","Turo adalah marketplace penyewaan kendaraan milik host.","Armada sewa lokal mungkin mendapat utilisasi tambahan lewat jadwal fleksibel.","Uji 10 kendaraan dengan satu operator; validasi okupansi dan insiden.","Perizinan, perlindungan, dan kecelakaan.",[3,4,4,5]],
  ["Kemasan guna ulang sebagai layanan","Produk","Wadah kirim dengan deposit, pengembalian, pencucian, dan pelacakan untuk merek.","Merek makanan & ritel","Managed service","Tinggi","Loop","https://www.loopstore.com/","Loop menguji model kemasan pakai ulang melalui sistem pengembalian.","Zona pengiriman padat dapat membuat ekonomi pengembalian lebih masuk akal.","Jalankan 200 wadah pada 3 merchant dalam radius 3 km.","Tingkat pengembalian dan biaya pencucian.",[3,2,3,5]],

  ["Paket kejutan makanan surplus","Kuliner","Jual stok makanan layak konsumsi menjelang tutup dengan harga khusus.","Bakery, kafe & pembeli hemat","Marketplace","Sedang","Too Good To Go","https://www.toogoodtogo.com/en-us","Too Good To Go menjual paket makanan surplus dari mitra usaha.","Klaster bakery dan kafe dapat menyediakan pasokan rutin pada jam tertentu.","Uji 10 merchant dan 100 paket selama dua pekan.","Konsistensi pasokan dan keamanan pangan.",[4,3,3,3]],
  ["Kolektif menu chef lokal","Kuliner","Menu siap santap dari beberapa chef dengan pemesanan mingguan dan distribusi bersama.","Profesional sibuk","Langganan","Tinggi","CookUnity","https://www.cookunity.com/","CookUnity menawarkan menu beragam dari chef dalam format pengantaran makanan.","Variasi chef dapat meningkatkan retensi dibanding meal prep satu merek.","Mulai dengan 3 chef dan 50 pelanggan mingguan.","Kualitas, pengiriman dingin, dan churn.",[4,4,4,5]],
  ["Oleh-oleh kuliner antarkota","Kuliner","Kurasi makanan khas tahan kirim dari produsen lokal dengan standar pengemasan.","Perantau & pembeli hadiah","Marketplace","Sedang","Goldbelly","https://www.goldbelly.com/","Goldbelly mengirim produk khas restoran dan produsen makanan lintas wilayah.","Produsen khas daerah dapat menjangkau pembeli di kota lain lewat kurasi.","Uji 10 produk dari 3 kota; pantau kerusakan kiriman.","Ketahanan produk dan ongkir.",[4,4,3,3]],
  ["Makan malam bersama host lokal","Kuliner","Reservasi meja kecil di rumah atau studio chef untuk pengalaman makan tematik.","Wisatawan & komunitas kuliner","Marketplace","Sedang","Eatwith","https://www.eatwith.com/","Eatwith memasarkan pengalaman makan yang dipandu host lokal.","Pengalaman terkurasi dapat menarik wisatawan yang ingin bertemu warga setempat.","Selenggarakan 8 sesi dengan 4 host; ukur keterisian.","Izin, keamanan pangan, dan kualitas host.",[3,2,4,3]],
  ["Kendali stok & margin dapur","Kuliner","Catat resep, stok, harga pemasok, dan margin menu pada satu dashboard.","Restoran multi cabang","SaaS","Sedang","MarketMan","https://www.marketman.com/","MarketMan menawarkan manajemen inventaris serta pembelian restoran.","Restoran kecil yang tumbuh mungkin butuh kontrol biaya bahan yang lebih mudah.","Integrasikan spreadsheet 5 restoran dan ukur waktu tutup stok.","Disiplin input data dan integrasi POS.",[4,4,4,3]],
  ["Diskon otomatis jelang kedaluwarsa","Kuliner","Aturan harga dinamis untuk produk segar berdasarkan sisa umur simpan.","Supermarket & toko segar","SaaS","Tinggi","Wasteless","https://www.wasteless.com/","Wasteless menawarkan markdown dinamis untuk produk yang mendekati tanggal kedaluwarsa.","Peritel dengan data tanggal yang rapi bisa menekan barang terbuang.","Uji satu lorong di 2 toko dan bandingkan waste mingguan.","Integrasi label harga dan data tanggal.",[4,2,4,5]],
  ["Jaringan donasi surplus pangan","Kuliner","Jadwalkan pengambilan surplus usaha ke komunitas penerima dengan bukti serah terima.","Hotel, katering & organisasi sosial","Managed service","Tinggi","Replate","https://www.replate.org/","Replate mengatur penyaluran surplus makanan dari organisasi ke penerima.","Bukti serah terima bisa membantu pelaku usaha mengelola program sosial rutin.","Jalankan 20 penjemputan di satu kawasan bisnis.","Keamanan pangan dan biaya rute.",[3,2,2,5]],
  ["Kulkas makan siap santap di kantor","Kuliner","Titik penjualan makanan dingin yang diisi ulang berdasarkan permintaan gedung.","Pengelola gedung & pekerja","Langganan","Tinggi","Everytable","https://everytable.com/","Everytable menjual makanan siap santap melalui berbagai kanal termasuk titik ritel.","Gedung dengan sedikit pilihan makan bisa menjadi lokasi uji yang menarik.","Pasang satu kulkas di gedung 300 pekerja; ukur sell-through.","Cold chain dan barang tidak terjual.",[3,3,3,5]],
  ["Dapur bersama spesialis delivery","Kuliner","Sewakan fasilitas masak per slot dengan utilitas dan layanan operasional bersama.","Merek makanan digital","Managed service","Tinggi","CloudKitchens","https://cloudkitchens.com/","CloudKitchens menyediakan dapur komersial untuk merek makanan.","Permintaan musiman bisa dilayani tanpa restoran permanen bila lokasi tepat.","Uji satu dapur bersama 4 merek selama 8 minggu.","Capex, sanitasi, dan kepadatan pesanan.",[3,4,4,5]],

  ["Day pass fasilitas hotel","Hotel","Jual akses kolam, spa, dan fasilitas hotel tanpa menginap.","Hotel & warga sekitar","Marketplace","Sedang","ResortPass","https://www.resortpass.com/","ResortPass menawarkan akses harian kolam, spa, dan fasilitas hotel.","Slot fasilitas yang sepi pada hari kerja bisa menjadi pendapatan tambahan.","Daftarkan 5 hotel di satu kota dan uji weekday pass.","Kapasitas, layanan, dan konflik dengan tamu menginap.",[4,3,4,3]],
  ["Kamar hotel hanya siang hari","Hotel","Pesan kamar 4–8 jam untuk transit, bekerja, atau istirahat.","Hotel kota & pelancong transit","Marketplace","Sedang","Dayuse","https://www.dayuse.com/","Dayuse menjual kamar hotel untuk penggunaan siang hari.","Okupansi siang di sekitar stasiun dan bandara bisa dimonetisasi.","Jual 50 slot dari 3 hotel; ukur okupansi incremental.","Housekeeping dan pengaturan inventaris kamar.",[4,3,4,3]],
  ["Sistem operasi penginapan kecil","Hotel","Satu tempat untuk reservasi, pembayaran, housekeeping, dan komunikasi tamu.","Hotel independen & homestay","SaaS","Sedang","Cloudbeds","https://www.cloudbeds.com/","Cloudbeds memasarkan sistem manajemen properti hospitality terintegrasi.","Penginapan kecil mungkin butuh alur lokal yang lebih sederhana dan terjangkau.","Uji 5 properti; ukur jam kerja admin yang berkurang.","Integrasi OTA dan migrasi data.",[4,4,4,3]],
  ["Check-in mandiri untuk hotel kecil","Hotel","Verifikasi tamu, pembayaran, dan instruksi akses sebelum kedatangan.","Hotel kota & apartel","SaaS","Tinggi","Mews","https://www.mews.com/en","Mews menyediakan alur check-in digital dan operasi hotel.","Properti dengan kedatangan larut malam dapat menghemat waktu front desk.","Pilot 100 tamu pada 2 properti; ukur antrean dan kegagalan akses.","Identitas, keamanan akses, dan integrasi PMS.",[3,4,4,4]],
  ["Optimasi kanal penjualan kamar","Hotel","Pantau tarif, inventaris, dan performa berbagai kanal penjualan.","Hotel independen","SaaS","Tinggi","SiteMinder","https://www.siteminder.com/","SiteMinder menawarkan distribusi dan sistem komersial bagi hotel.","Operator kecil mungkin membutuhkan rekomendasi harga dengan setup ringan.","Tawarkan audit harga ke 10 hotel; ukur kenaikan pendapatan per kamar.","Akses data OTA dan akurasi rekomendasi.",[4,5,4,4]],
  ["Penyimpanan bagasi mitra toko","Hotel","Toko tepercaya menyimpan bagasi wisatawan per jam dengan bukti digital.","Wisatawan & toko dekat simpul transit","Marketplace","Sedang","LuggageHero","https://luggagehero.com/","LuggageHero memungkinkan reservasi penyimpanan bagasi pada lokasi mitra.","Area wisata padat bisa mendukung titik bagasi dengan tambahan pendapatan toko.","Uji 10 toko di satu koridor wisata; ukur volume harian.","Keamanan barang dan jam operasional.",[3,3,3,3]],
  ["Pengalaman kota oleh warga lokal","Hotel","Aktivitas kecil yang dipandu host terverifikasi dan bisa dipesan tamu hotel.","Wisatawan & pemandu lokal","Marketplace","Sedang","Withlocals","https://www.withlocals.com/","Withlocals menawarkan tur privat dan pengalaman lokal oleh host.","Hotel butik dapat menjual kegiatan yang lebih personal di luar paket tur umum.","Kurasi 10 host bersama 3 hotel; uji 50 pemesanan.","Mutu host, keamanan, dan musim wisata.",[4,4,3,3]],
  ["Kabin mikro untuk rehat singkat","Hotel","Jaringan kabin kecil di dekat kota dengan pemesanan digital dan operasi terpusat.","Pekerja urban & pemilik lahan","Managed service","Tinggi","Unyoked","https://unyoked.co/","Unyoked menampilkan jaringan kabin terpencil untuk short escape.","Lahan dekat kota dapat menawarkan perjalanan singkat yang mudah direncanakan.","Pilot satu kabin dengan mitra lahan; ukur okupansi 90 hari.","Perizinan lahan, akses, dan capex.",[3,3,4,5]],
  ["Operasi vila untuk rombongan","Hotel","Standar layanan, reservasi, dan upsell untuk vila keluarga dan grup.","Pemilik vila & wisatawan grup","Managed service","Tinggi","AvantStay","https://www.avantstay.com/","AvantStay mengelola dan memasarkan akomodasi untuk perjalanan grup.","Vila independen dapat memperoleh nilai dari operasional seragam dan distribusi.","Kelola 3 vila di satu destinasi; ukur ADR dan biaya layanan.","Kualitas properti dan operasi lapangan.",[4,4,4,5]],

  ["Sewa ruang fleksibel per jam","Lainnya","Temukan ruang untuk rapat, syuting, workshop, atau acara komunitas.","Pemilik ruang & penyelenggara","Marketplace","Sedang","Peerspace","https://www.peerspace.com/","Peerspace menyediakan pemesanan ruang berdasarkan kegiatan dan jam.","Ruang komersial yang kosong pada jam tertentu bisa menambah pendapatan.","Kurasi 30 ruang di satu kota; ukur pemesanan berulang.","Aturan gedung, kerusakan, dan akuisisi pasokan.",[4,3,4,3]],
  ["Sewa kolam dan fasilitas privat","Lainnya","Reservasi kolam atau lapangan privat per jam dari pemilik terverifikasi.","Keluarga & pemilik fasilitas","Marketplace","Sedang","Swimply","https://swimply.com/","Swimply memasarkan penyewaan kolam pribadi berdasarkan jam.","Pemilik fasilitas nonpublik bisa membuka slot terbatas di area perkotaan.","Uji 10 lokasi, izin tamu, dan 100 sesi.","Keselamatan, tetangga, dan tanggung jawab pemilik.",[3,2,4,3]],
  ["Gudang mini dari ruang menganggur","Lainnya","Pasangkan kebutuhan simpan bulanan dengan garasi dan ruang kosong terverifikasi.","Warga kota & pemilik ruang","Marketplace","Tinggi","Neighbor","https://www.neighbor.com/","Neighbor menghubungkan penyewa penyimpanan dengan pemilik ruang dan parkir.","Barang musiman dapat menciptakan permintaan penyimpanan di lokasi dekat rumah.","Uji 15 lokasi dan 30 penyewa dengan inspeksi awal.","Keamanan, asuransi, dan aturan bangunan.",[3,3,3,4]],
  ["Sewa peralatan produksi film","Lainnya","Jaringan kamera dan perlengkapan syuting profesional dengan kalender serta pemeriksaan.","Studio kecil & kreator","Marketplace","Tinggi","ShareGrid","https://www.sharegrid.com/","ShareGrid menampilkan penyewaan kamera, lensa, dan alat produksi.","Kreator lokal mungkin membutuhkan perlengkapan spesifik sesekali tanpa membeli.","Daftarkan 20 pemilik alat di satu komunitas produksi.","Nilai alat tinggi dan jadwal yang berubah.",[3,3,4,4]],
  ["Gudang fleksibel untuk lonjakan pesanan","Lainnya","Marketplace kapasitas gudang dan pemenuhan pesanan untuk periode puncak.","Merek e-commerce & operator gudang","Marketplace","Tinggi","Flexe","https://flexe.com/","Flexe menawarkan jaringan gudang fleksibel dan layanan fulfillment.","Penjual musiman dapat menghindari kontrak gudang jangka panjang.","Uji 2 gudang dan 5 merek pada satu musim promosi.","Standar SLA dan integrasi stok.",[4,4,4,5]],
  ["Jasa rumah dengan harga transparan","Lainnya","Pemesanan tugas kecil seperti pemasangan, perakitan, dan pemindahan barang.","Rumah tangga & penyedia jasa","Marketplace","Sedang","Taskrabbit","https://www.taskrabbit.com/","Taskrabbit memasarkan bantuan tugas rumah berdasarkan kategori dan jadwal.","Kategori yang sangat spesifik bisa lebih mudah dipercaya daripada direktori jasa umum.","Uji satu kategori dengan 20 teknisi dan 100 pesanan.","Mutu layanan dan biaya akuisisi.",[4,5,3,3]],
  ["Penitipan hewan terverifikasi","Lainnya","Cari pengasuh hewan dekat rumah dengan ketersediaan, ulasan, dan pembaruan harian.","Pemilik hewan & pengasuh","Marketplace","Sedang","Rover","https://www.rover.com/","Rover menyediakan pemesanan pengasuhan, jalan, dan penitipan hewan.","Pemilik hewan di kota besar dapat membutuhkan opsi terverifikasi saat bepergian.","Uji 20 sitter dan 50 booking; ukur repeat dan insiden.","Keamanan hewan dan kepercayaan.",[4,4,4,3]],
  ["Sistem reservasi studio kebugaran","Lainnya","Paket jadwal, pembayaran, keanggotaan, dan pengingat untuk studio independen.","Studio yoga, pilates & kebugaran","SaaS","Sedang","Mindbody","https://www.mindbodyonline.com/","Mindbody menyediakan perangkat lunak operasional untuk bisnis wellness.","Studio kecil mungkin memilih solusi lebih ringkas dengan pembayaran lokal.","Pilot 5 studio dan ukur kehadiran serta no-show.","Integrasi pembayaran dan retensi bisnis.",[4,4,4,3]],
  ["Jaringan titik pengambilan paket","Lainnya","Toko lingkungan menjadi titik serah terima paket dan retur terjadwal.","Penjual online & toko mitra","Managed service","Tinggi","Stasher","https://stasher.com/","Stasher menunjukkan model jaringan toko mitra untuk penitipan barang.","Jaringan mitra yang sama berpotensi dipakai untuk serah terima paket kecil.","Uji 8 toko dan satu mitra logistik untuk 200 paket.","Integrasi kurir dan tanggung jawab kehilangan.",[3,4,3,5]]
];

export const ideas = [...raw, ...extraRaw].map((r, i) => ({
  id: i + 1, title: r[0], category: r[1], summary: r[2], customer: r[3], model: r[4], complexity: r[5],
  example: r[6], source: r[7], evidence: r[8], hypothesis: r[9], pilot: r[10], risk: r[11],
  ratings: { potential: r[12][0], competition: r[12][1], monetization: r[12][2], difficulty: r[12][3] }
}));
